### ISSUE TITLE
TypeError: 'timespec' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by tyzbit** [esotericnonsense/bitcoind-ncurses2#1]
$ python3 main.py

    cookiefile not found, falling back to password authentication
    Traceback (most recent call last):
      File "main.py", line 243, in <module>
        mainfn()
      File "main.py", line 232, in mainfn
        loop.run_until_complete(t)
      File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
        return future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(None)
      File "/home/bitcoinuser/bitcoind-ncurses/splash.py", line 66, in draw
        await self._end_splash(nosplash)
      File "/home/bitcoinuser/bitcoind-ncurses/splash.py", line 73, in _end_splash
        await self._set_mode_callback(DEFAULT_MODE)
      File "/home/bitcoinuser/bitcoind-ncurses/modes.py", line 50, in set_mode
        await self._call_callbacks(self._mode, newmode)
      File "/home/bitcoinuser/bitcoind-ncurses/modes.py", line 44, in _call_callbacks
        await bcb(newmode)
      File "/home/bitcoinuser/bitcoind-ncurses/footer.py", line 65, in on_mode_change
        await self.draw()
      File "/home/bitcoinuser/bitcoind-ncurses/footer.py", line 50, in draw
        await self._draw()
      File "/home/bitcoinuser/bitcoind-ncurses/footer.py", line 44, in _draw
        self._pad.addstr(0, 81, self._dt.isoformat(timespec="seconds")[:19], CYELLOW + CBOLD)
    TypeError: 'timespec' is an invalid keyword argument for this function
    Task exception was never retrieved
    future: <Task finished coro=<tick() done, defined at main.py:62> exception=TypeError("'timespec' is an invalid keyword argument for this function",)>
    Traceback (most recent call last):
      File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(None)
      File "main.py", line 68, in tick
        await callback(dt)
      File "main.py", line 165, in on_tick
        await footerview.on_tick(dt)
      File "/home/bitcoinuser/bitcoind-ncurses/footer.py", line 69, in on_tick
        await self.draw()
      File "/home/bitcoinuser/bitcoind-ncurses/footer.py", line 50, in draw
        await self._draw()
      File "/home/bitcoinuser/bitcoind-ncurses/footer.py", line 44, in _draw
        self._pad.addstr(0, 81, self._dt.isoformat(timespec="seconds")[:19], CYELLOW + CBOLD)
    TypeError: 'timespec' is an invalid keyword argument for this function

Let me know if there's any further info that would be helpful in debugging.

**Comment by esotericnonsense** [comment]
Python 3.6 added the timespec argument to datetime.isoformat. Without it, decimal seconds are enabled.
Upgrading to Python 3.6 is probably the easiest way to fix this, alternately we could add in a helper function that catches the TypeError and tries to truncate it in some other way.

**Comment by tyzbit** [comment]
If I had read the README, I'd have the right dependencies 😊 
Unfortunately, Ubuntu's repos are woefully out of date and I can't install 3.6 but that's not your problem.

**Comment by esotericnonsense** [comment]
If you can, a6ae0e464ef1270ca8e9cf25d14d5aa6f16216b7 is an attempt to fix this issue - I haven't tested it on py3.5 but it should work.

**Comment by tyzbit** [comment]
Pulled down latest and it runs great on python 3.5, not sure how far back we could go but this makes it compatible at least with what's in the repo for the current LTS of Ubuntu (16.04).  Thanks for the quick fix 👍

**Comment by esotericnonsense** [comment]
Awesome! Yeah, I think at least 3.5 is worth supporting for that reason.
When I get some time I'll chuck up a few VM's and see where it breaks.
