### ISSUE TITLE
TypeError: 'timespec' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by in3rsha** [esotericnonsense/bitcoind-ncurses2#10]
Hi there,

I have very little experience with Python, so this could well be a mistake on my part.

However, after installing, when I run `python3 main.py` I see the splash screen, but the I get the following errror:

```
cookiefile not found, falling back to password authentication
Traceback (most recent call last):
  File "main.py", line 243, in <module>
    mainfn()
  File "main.py", line 232, in mainfn
    loop.run_until_complete(t)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/user/bitcoin/bitcoind-ncurses2/splash.py", line 66, in draw
    await self._end_splash(nosplash)
  File "/home/user/bitcoin/bitcoind-ncurses2/splash.py", line 73, in _end_splash
    await self._set_mode_callback(DEFAULT_MODE)
  File "/home/user/bitcoin/bitcoind-ncurses2/modes.py", line 50, in set_mode
    await self._call_callbacks(self._mode, newmode)
  File "/home/user/bitcoin/bitcoind-ncurses2/modes.py", line 44, in _call_callbacks
    await bcb(newmode)
  File "/home/user/bitcoin/bitcoind-ncurses2/footer.py", line 65, in on_mode_change
    await self.draw()
  File "/home/user/bitcoin/bitcoind-ncurses2/footer.py", line 50, in draw
    await self._draw()
  File "/home/user/bitcoin/bitcoind-ncurses2/footer.py", line 44, in _draw
    self._pad.addstr(0, 81, self._dt.isoformat(timespec="seconds")[:19], CYELLOW + CBOLD)
TypeError: 'timespec' is an invalid keyword argument for this function
```

Is this something I can fix?

**Comment by nshopik** [comment]
look in #1 i believe it was fixed just yesterday

**Comment by in3rsha** [comment]
Ah yes, thank you.
