### ISSUE TITLE
RPC timeouts are not handled

### ISSUE THREAD

**Issue by esotericnonsense** [esotericnonsense/bitcoind-ncurses2#3]

**Comment by maxya** [comment]
RPC timeout causes crash.. 

How to reproduce - run main.py, wait 10 seconds.. 

`
bob@coin:~/bitcoind-ncurses2$ python3 main.py
cookiefile not found, falling back to password authentication
Traceback (most recent call last):
  File "/home/bob/bitcoind-ncurses2/rpc.py", line 128, in _fetch
    async with session.post(self._url, headers=self._headers, data=req) as response:
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client.py", line 690, in __aenter__
    self._resp = yield from self._coro
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client.py", line 277, in _request
    yield from resp.start(conn, read_until_eof)
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 624, in start
    (message, payload) = yield from self._protocol.read()
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/streams.py", line 554, in read
    yield from self._waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 285, in result
    raise CancelledError
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bob/bitcoind-ncurses2/rpc.py", line 129, in _fetch
    return await response.text()
  File "/home/bob/.local/lib/python3.5/site-packages/async_timeout/__init__.py", line 35, in __exit__
    self._do_exit(exc_type)
  File "/home/bob/.local/lib/python3.5/site-packages/async_timeout/__init__.py", line 80, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 261, in <module>
    mainfn()
  File "main.py", line 250, in mainfn
    loop.run_until_complete(t)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 307, in _wakeup
    self._step(exc)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "main.py", line 64, in poll_client
    await callback(method, d)
  File "main.py", line 176, in on_bestblockhash
    await blockview.on_bestblockhash(key, obj)
  File "/home/bob/bitcoind-ncurses2/block.py", line 416, in on_bestblockhash
    await self._blockstore.on_bestblockhash(bestblockhash)
  File "/home/bob/bitcoind-ncurses2/block.py", line 106, in on_bestblockhash
    block = await self.get_block(blockhash)
  File "/home/bob/bitcoind-ncurses2/block.py", line 30, in get_block
    j = await self._client.request("getblock", [blockhash])
  File "/home/bob/bitcoind-ncurses2/rpc.py", line 142, in request
    j = await self._fetch(session, req)
  File "/home/bob/bitcoind-ncurses2/rpc.py", line 131, in _fetch
    raise RPCTimeoutError
rpc.RPCTimeoutError
Task was destroyed but it is pending!
task: <Task pending coro=<ThreadedResolver.resolve() done, defined at /home/bob/.local/lib/python3.5/site-packages/aiohttp/resolver.py:28> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:452, Task._wakeup()]> cb=[shield.<locals>._done_callback() at /usr/lib/python3.5/asyncio/tasks.py:719]>
Task was destroyed but it is pending!
task: <Task pending coro=<ThreadedResolver.resolve() done, defined at /home/bob/.local/lib/python3.5/site-packages/aiohttp/resolver.py:28> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:452, Task._wakeup()]> cb=[shield.<locals>._done_callback() at /usr/lib/python3.5/asyncio/tasks.py:719]>
Exception ignored in: <coroutine object poll_client at 0x7fb26f065d00>
Traceback (most recent call last):
  File "main.py", line 58, in poll_client
  File "/home/bob/bitcoind-ncurses2/rpc.py", line 142, in request
  File "/home/bob/bitcoind-ncurses2/rpc.py", line 128, in _fetch
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client.py", line 690, in __aenter__
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client.py", line 280, in _request
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 111, in close
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 495, in _release
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client_proto.py", line 52, in close
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 622, in close
  File "/usr/lib/python3.5/asyncio/base_events.py", line 572, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 357, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object poll_client at 0x7fb26f0659e8>
Traceback (most recent call last):
  File "main.py", line 58, in poll_client
  File "/home/bob/bitcoind-ncurses2/rpc.py", line 142, in request
  File "/home/bob/bitcoind-ncurses2/rpc.py", line 128, in _fetch
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client.py", line 690, in __aenter__
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client.py", line 280, in _request
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 111, in close
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 495, in _release
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client_proto.py", line 52, in close
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 622, in close
  File "/usr/lib/python3.5/asyncio/base_events.py", line 572, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 357, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object poll_client at 0x7fb26f065938>
Traceback (most recent call last):
  File "main.py", line 58, in poll_client
  File "/home/bob/bitcoind-ncurses2/rpc.py", line 142, in request
  File "/home/bob/bitcoind-ncurses2/rpc.py", line 128, in _fetch
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client.py", line 690, in __aenter__
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client.py", line 280, in _request
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 111, in close
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 495, in _release
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client_proto.py", line 52, in close
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 622, in close
  File "/usr/lib/python3.5/asyncio/base_events.py", line 572, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 357, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object poll_client at 0x7fb26f065780>
Traceback (most recent call last):
  File "main.py", line 58, in poll_client
  File "/home/bob/bitcoind-ncurses2/rpc.py", line 142, in request
  File "/home/bob/bitcoind-ncurses2/rpc.py", line 128, in _fetch
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client.py", line 690, in __aenter__
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client.py", line 280, in _request
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 111, in close
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 495, in _release
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client_proto.py", line 52, in close
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 622, in close
  File "/usr/lib/python3.5/asyncio/base_events.py", line 572, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 357, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object poll_client at 0x7fb26f0657d8>
Traceback (most recent call last):
  File "main.py", line 58, in poll_client
  File "/home/bob/bitcoind-ncurses2/rpc.py", line 142, in request
  File "/home/bob/bitcoind-ncurses2/rpc.py", line 128, in _fetch
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client.py", line 690, in __aenter__
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client.py", line 280, in _request
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 111, in close
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 495, in _release
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client_proto.py", line 52, in close
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 622, in close
  File "/usr/lib/python3.5/asyncio/base_events.py", line 572, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 357, in _check_closed
RuntimeError: Event loop is closed
Task exception was never retrieved
future: <Task finished coro=<poll_client() done, defined at main.py:52> exception=RPCTimeoutError()>
Traceback (most recent call last):
  File "/home/bob/bitcoind-ncurses2/rpc.py", line 128, in _fetch
    async with session.post(self._url, headers=self._headers, data=req) as response:
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client.py", line 690, in __aenter__
    self._resp = yield from self._coro
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client.py", line 277, in _request
    yield from resp.start(conn, read_until_eof)
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 624, in start
    (message, payload) = yield from self._protocol.read()
  File "/home/bob/.local/lib/python3.5/site-packages/aiohttp/streams.py", line 554, in read
    yield from self._waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 285, in result
    raise CancelledError
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bob/bitcoind-ncurses2/rpc.py", line 129, in _fetch
    return await response.text()
  File "/home/bob/.local/lib/python3.5/site-packages/async_timeout/__init__.py", line 35, in __exit__
    self._do_exit(exc_type)
  File "/home/bob/.local/lib/python3.5/site-packages/async_timeout/__init__.py", line 80, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 261, in <module>
    mainfn()
  File "main.py", line 250, in mainfn
    loop.run_until_complete(t)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 307, in _wakeup
    self._step(exc)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "main.py", line 64, in poll_client
    await callback(method, d)
  File "main.py", line 176, in on_bestblockhash
    await blockview.on_bestblockhash(key, obj)
  File "/home/bob/bitcoind-ncurses2/block.py", line 416, in on_bestblockhash
    await self._blockstore.on_bestblockhash(bestblockhash)
  File "/home/bob/bitcoind-ncurses2/block.py", line 106, in on_bestblockhash
    block = await self.get_block(blockhash)
  File "/home/bob/bitcoind-ncurses2/block.py", line 30, in get_block
    j = await self._client.request("getblock", [blockhash])
  File "/home/bob/bitcoind-ncurses2/rpc.py", line 142, in request
    j = await self._fetch(session, req)
  File "/home/bob/bitcoind-ncurses2/rpc.py", line 131, in _fetch
    raise RPCTimeoutError
rpc.RPCTimeoutError

`
