### ISSUE TITLE
_curses.error: addwstr() returned ERR

### ISSUE THREAD

**Issue by darwin** [esotericnonsense/bitcoind-ncurses2#5]
The app launches. All seems to work. But switching to the "peers" screen fails. My bitcoind is v0.15 compiled from sources with disabled wallet (`./configure --without-gui --disable-tests --disable-wallet`).

```
Traceback (most recent call last):
  File "/Users/darwin/bitcoind-ncurses2/main.py", line 243, in <module>
    mainfn()
  File "/Users/darwin/bitcoind-ncurses2/main.py", line 232, in mainfn
    loop.run_until_complete(t)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/Users/darwin/bitcoind-ncurses2/main.py", line 49, in keypress_loop
    await handle_keypress(key)
  File "/Users/darwin/bitcoind-ncurses2/main.py", line 35, in handle_keypress
    key = await callback(key)
  File "/Users/darwin/bitcoind-ncurses2/modes.py", line 87, in handle_keypress
    await self._seek_mode(1)
  File "/Users/darwin/bitcoind-ncurses2/modes.py", line 62, in _seek_mode
    await self.set_mode(newmode)
  File "/Users/darwin/bitcoind-ncurses2/modes.py", line 50, in set_mode
    await self._call_callbacks(self._mode, newmode)
  File "/Users/darwin/bitcoind-ncurses2/modes.py", line 40, in _call_callbacks
    await cb2(newmode)
  File "/Users/darwin/bitcoind-ncurses2/view.py", line 44, in on_mode_change
    await self._draw_if_visible()
  File "/Users/darwin/bitcoind-ncurses2/view.py", line 36, in _draw_if_visible
    await self._draw()
  File "/Users/darwin/bitcoind-ncurses2/peers.py", line 85, in _draw
    self._pad.addstr(1+index-offset, 93, str(peer['synced_headers']).rjust(7)    )
_curses.error: addwstr() returned ERR
```

```
> python3 --version
Python 3.6.2
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1611
```

**Comment by esotericnonsense** [comment]
Thank you for reporting this.

I think this is a simple one - in haste, I forgot to implement scrolling in the peers view.
So if you have more than ~17 peers or so it will attempt to draw outside the pad and crash.
Should be able to fix that tonight.

**Comment by darwin** [comment]
Yep, I had ~90 peers.

No hurry. And btw/ thanks for resurrecting development of this project.

**Comment by esotericnonsense** [comment]
No problem! I'm going to add an issue for handling curses errors more generally (because it doesn't make sense to bring down the house simply because something doesn't fit on the screen), but that'll be a job for later. :)

**Comment by esotericnonsense** [comment]
7d45bd81a76f8e238c1a1bea126ebd2cd6d97440 is a temporary fix for this issue. It doesn't implement scrolling, just stops drawing after the first 15 peers.

**Comment by darwin** [comment]
Confirmed. 7d45bd81a76f8e238c1a1bea126ebd2cd6d97440 fixed the crash for me.
