### ISSUE TITLE
Gracefully handle pruning nodes

### ISSUE THREAD

**Issue by tyzbit** [esotericnonsense/bitcoind-ncurses2#6]
I run a pruning node, and navigating to a block which is not present on disk results in the following error:

      Traceback (most recent call last):
      File "/home/bitcoinuser/bitcoind-ncurses/main.py", line 243, in <module>
        mainfn()
      File "/home/bitcoinuser/bitcoind-ncurses/main.py", line 232, in mainfn
        loop.run_until_complete(t)
      File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
        return future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(None)
      File "/home/bitcoinuser/bitcoind-ncurses/main.py", line 49, in keypress_loop
        await handle_keypress(key)
      File "/home/bitcoinuser/bitcoind-ncurses/main.py", line 35, in handle_keypress
        key = await callback(key)
      File "/home/bitcoinuser/bitcoind-ncurses/modes.py", line 76, in handle_keypress
        key = await handler(key)
      File "/home/bitcoinuser/bitcoind-ncurses/block.py", line 452, in handle_keypress
        await self._select_previous_block()
      File "/home/bitcoinuser/bitcoind-ncurses/block.py", line 355, in _select_previous_block
        newhash = await self._blockstore.get_previousblockhash(self._hash)
      File "/home/bitcoinuser/bitcoind-ncurses/block.py", line 42, in get_previousblockhash
        return self._blocks[blockhash]["previousblockhash"]
      TypeError: 'NoneType' object is not subscriptable

Steps to reproduce:
(prereq: run a pruning node)
* go to block viewer
* hit TAB and enter a block number not on disk (I prune at 550MB and block 487000 is sufficiently old enough not to be on disk)
* press J or K

**Comment by esotericnonsense** [comment]
Thank you for reporting this. This is related to #4; I'll test this again once the RPC error handling is implemented.

**Comment by esotericnonsense** [comment]
I think it will also crash on viewing most transactions if txindex is not on for similar reasons (it may simply display 'no transaction loaded', I'll test that later).

**Comment by unsystemizer** [comment]
@esotericnonsense correct.

Navigated to "wallet" while running `bitcoind -reindex`:

```
cookiefile not found, falling back to password authentication
Traceback (most recent call last):
  File "main.py", line 261, in <module>
    mainfn()
  File "main.py", line 250, in mainfn
    loop.run_until_complete(t)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "main.py", line 49, in keypress_loop
    await handle_keypress(key)
  File "main.py", line 35, in handle_keypress
    key = await callback(key)
  File "/home/user/bitcoind-ncurses2/modes.py", line 87, in handle_keypress
    await self._seek_mode(1)
  File "/home/user/bitcoind-ncurses2/modes.py", line 62, in _seek_mode
    await self.set_mode(newmode)
  File "/home/user/bitcoind-ncurses2/modes.py", line 50, in set_mode
    await self._call_callbacks(self._mode, newmode)
  File "/home/user/bitcoind-ncurses2/modes.py", line 40, in _call_callbacks
    await cb2(newmode)
  File "/home/user/bitcoind-ncurses2/view.py", line 44, in on_mode_change
    await self._draw_if_visible()
  File "/home/user/bitcoind-ncurses2/view.py", line 36, in _draw_if_visible
    await self._draw()
  File "/home/user/bitcoind-ncurses2/wallet.py", line 73, in _draw
    await self._draw_wallet(self._wallet)
  File "/home/user/bitcoind-ncurses2/wallet.py", line 62, in _draw_wallet
    self._pad.addstr(2+((i-offset)*3), 30, "block: {: 7d}".format(tx["blockindex"]), color)
KeyError: 'blockindex'
```
