### ISSUE TITLE
KeyError: 'weight' on 0.14 bitcoind

### ISSUE THREAD

**Issue by nshopik** [esotericnonsense/bitcoind-ncurses2#9]
I didn't test with 0.15 though but 0.14 fails with this exception, but I'm not quite sure what exactly is failing here. Pretty sure 0.15 didn't introduce any new rpc commands

```
cookiefile not found, falling back to password authentication
Traceback (most recent call last):
  File "main.py", line 261, in <module>
    mainfn()
  File "main.py", line 250, in mainfn
    loop.run_until_complete(t)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/shopik/bitcoind-ncurses2/splash.py", line 66, in draw
    await self._end_splash(nosplash)
  File "/home/shopik/bitcoind-ncurses2/splash.py", line 73, in _end_splash
    await self._set_mode_callback(DEFAULT_MODE)
  File "/home/shopik/bitcoind-ncurses2/modes.py", line 50, in set_mode
    await self._call_callbacks(self._mode, newmode)
  File "/home/shopik/bitcoind-ncurses2/modes.py", line 40, in _call_callbacks
    await cb2(newmode)
  File "/home/shopik/bitcoind-ncurses2/view.py", line 44, in on_mode_change
    await self._draw_if_visible()
  File "/home/shopik/bitcoind-ncurses2/monitor.py", line 152, in _draw_if_visible
    await self._draw()
  File "/home/shopik/bitcoind-ncurses2/monitor.py", line 74, in _draw
    bb["weight"]
KeyError: 'weight'
```

**Comment by esotericnonsense** [comment]
Odd. It's coming from getblock. "weight" was in 0.14.0 according to this:
https://github.com/bitcoin/bitcoin/blob/v0.14.0/src/rpc/blockchain.cpp

Not sure what's going on here. Can you try `bitcoin-cli getblock 000000000000056f90f3cf4b20f312c95276657afedd5615eecb70dd1548f1d1` and see if it has a "weight" field?

**Comment by nshopik** [comment]
Ah now make sense, I was running on BCH blockchain, which doesn't have that since no segwit there. Guess I need make patch for that

**Comment by Shellcat-Zero** [comment]
Is this fixed yet?  I just cloned and ran the repo, and I'm getting the same error with the BCH full node.
```
bitcoind -version
Bitcoin ABC Daemon version v0.15.0.0-unk
Copyright (C) 2009-2017 The Bitcoin developers
Copyright (C) 2009-2017 The Bitcoin Core developers

Please contribute if you find Bitcoin ABC useful. Visit
<https://www.bitcoinabc.org> for further information about the software.
The source code is available from <https://github.com/Bitcoin-ABC/bitcoin-abc>.

This is experimental software.
Distributed under the MIT software license, see the accompanying file COPYING
or <https://opensource.org/licenses/MIT>

This product includes software developed by the OpenSSL Project for use in the
OpenSSL Toolkit <https://www.openssl.org> and cryptographic software written by
Eric Young and UPnP software written by Thomas Bernard.
```

Or what do I need to do to fix this?

**Comment by esotericnonsense** [comment]
Bcash doesn't have weight because it's not segwit-enabled.

In the future I expect more segwit-related functionality to make its' way into this software and personally I have no interest in maintaining compatibility.

In this specific case you could probably just grep the codebase for segwit-related stuff and comment it out.

If someone is interested they could maintain a patch set, I guess.
